apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-with-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-with-quarkus
  template:
    metadata:
      labels:
        app: code-with-quarkus
    spec:
      containers:
        - name: code-with-quarkus
          image: codecaveofandrew/code-with-quarkus:latest
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:mysql://localhost:3306/sakila
            - name: QUARKUS_DATASOURCE_USERNAME
              value: root
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: sakila
        - name: sakila-db
          image: restsql/mysql-sakila
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: sakila
            - name: MYSQL_DATABASE
              value: sakila
          ports:
            - containerPort: 3306